swagger: "2.0"
info:
  version: "0.0.1"
  title: servicioClientes
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /cliente:
    # our controller name
    x-swagger-router-controller: cliente
    get:
      operationId: getAll
      description: obtiene la lista de clientes
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetClientes"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GetClientes"
    post:
      operationId: save
      description: agregar nuevo cliente
      parameters:
        - name: nombre
          description: nombre del cliente
          in: body
          required: true
          schema:
            $ref: "#/definitions/Cliente"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GeneralResponse" 
            
  /cliente/{cedula}:
    x-swagger-router-controller: cliente
    get:
      operationId: getByCedula
      description: obtener un cliente por cedula
      parameters:
        - name: cedula 
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetClientePorCedula"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GetClientePorCedula"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetClientes:
    required:
      - clientes
    properties:
      clientes:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            nombre:
              type: string
            fechaNacimiento:
              type: string 
            cedula:
              type: string
            domicilio:
              type: string
            nroTarjetaCredito:
              type: string
  Cliente:
    type: object
    properties:
      nombre:
        type: string
        description: nombre del cliente
      fechaNacimiento:
        type: string
        description: fecha de nacimiento del cliente
      cedula:
        type: string
        description: cedula del cliente
      domicilio:
        type: string
        description: domicilio del cliente
      nroTarjetaCredito:
        type: string
        description: Nro. de tarjeta de credito del cliente
    required:
      - nombre
      - fechaNacimiento
      - cedula
      - domicilio
      - nroTarjetaCredito
      
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
      
  GetClientePorCedula:
    required:
      - nombre
      - fechaNacimiento
      - cedula
      - domicilio
      - nroTarjetaCredito
    properties:
      nombre:
        type: string
        description: nombre del cliente
      fechaNacimiento:
        type: string
        description: fecha de nacimiento del cliente
      cedula:
        type: string
        description: cedula del cliente
      domicilio:
        type: string
        description: domicilio del cliente
      nroTarjetaCredito:
        type: string
        description: Nro. de tarjeta de credito del cliente    
      
 